### ISSUE TITLE
Bundling into a single archive download?

### ISSUE THREAD

**Issue by lheydon** [FadeMind/W-ICO#26]
@FadeMind, thanks for this awesome collection but if I'm not mistaken these all currently need to be downloaded individually from Github?

Would it be possible to place them all into a single archive (with the existing folder structure intact) so that they can be downloaded and quickly previewed and utilised on a Windows system instead?

Thanks!

**Comment by FadeMind** [comment]
@lheydon See
![20231116-1700114768](https://github.com/FadeMind/W-ICO/assets/9846948/ab65e892-ee7b-421f-9015-a175fe20d320)

![20231116-1700114815](https://github.com/FadeMind/W-ICO/assets/9846948/e545af75-a269-45ee-a08e-4a64962a1186)

**Comment by lheydon** [comment]
**@FadeMind**, oh excellent, thanks for pointing this out. As a non-programmer, Github is confusing as all hell for me! 😲
